import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState, FunctionComponent, useEffect } from "react";
import { useConnectors, useAccount, useStarknet } from "@starknet-react/core";
import { useMinified, useUpdatedDomainFromAddress } from '@/hooks/displayname';

export default function Home() {

  // connection
  const [hasWallet, setHasWallet] = useState<boolean>(true);
  const [isWrongNetwork, setIsWrongNetwork] = useState(false);

  // starknet-react
  const { address } = useAccount();
  const { available, connect, disconnect } = useConnectors();

  const domain = useUpdatedDomainFromAddress(address);

  function disconnectByClick(): void {
    disconnect();
    setIsWrongNetwork(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <button
          onClick={
            address
              ? () => disconnectByClick()
              : available.length === 1
                ? () => connect(available[0])
                : () => setHasWallet(true)
          }
        >
          {address ? (

            <div>
              {domain
                ? useMinified(domain)
                : useMinified(address ?? "")}
            </div>

          ) : (
            "connect"
          )}
        </button>


      </main>
    </>
  )
}
